import "./style.css";
import { initI18n } from "./i18n";
import { initNav } from "./nav";
import { initHero } from "./hero";
import { initStats } from "./stats";
import { initTerminal } from "./terminal";
import { initPipeline } from "./pipeline";
import { initCommitFlow } from "./commitFlow";
import { initInteractive } from "./interactive";
import { initFeatures } from "./features";
import { initArchitecture } from "./architecture";
import { initStackCards } from "./stackCards";
import { initControlCards } from "./controlCards";
import { initGetStarted } from "./getStarted";
import { initCursor } from "./cursor";
import { initScrollProgress } from "./scrollProgress";
import { initCarousel } from "./carousel";

initI18n();
initNav();
initScrollProgress();
initCursor();
initHero();
initStats();
initTerminal();
initPipeline();
initCommitFlow();
initInteractive();
initFeatures();
initCarousel();
initArchitecture();
initStackCards();
initControlCards();
initGetStarted();
