import "./style.css";
import { initI18n } from "./i18n";
import { initHero } from "./hero";
import { initStats } from "./stats";
import { initTerminal } from "./terminal";
import { initPipeline } from "./pipeline";
import { initFeatures } from "./features";
import { initArchitecture } from "./architecture";
import { initStackCards } from "./stackCards";
import { initGetStarted } from "./getStarted";
import { initCursor } from "./cursor";
import { initScrollProgress } from "./scrollProgress";

initI18n();
initScrollProgress();
initCursor();
initHero();
initStats();
initTerminal();
initPipeline();
initFeatures();
initArchitecture();
initStackCards();
initGetStarted();
